"""
delete_transitory_data.py

Description:  Delete transitory data generated by the Automated Status Tool 
              from output folders. This script can be run standalone or imported
              as a module.
              
              Transitory data includes:
              - aoi_boundary.gdb              (intermediate AOI geodatabase)
              - one_status_common_datasets_aoi.gdb
              - one_status_tabs_1_and_2_datasets.gdb
              - auto_status.log               (per-run AST log file)
              - input_list.json               (per-run query manifest)

              The deliverable outputs (maps/ folder and the final .xlsx report)
              are NOT deleted.

Author:  GitHub Copilot
         Based on work by Mike Eastwood and the AST team
"""

import os
import shutil
import logging


# Default output folder path — no hardcoded path; user must supply via CLI argument
DEFAULT_OUTPUT_FOLDER = ""


# Define transitory data items to delete.
# These are the intermediate files produced by the auto_status runner that are
# NOT part of the final deliverable; they can be safely removed after the batch
# run is validated.
TRANSITORY_ITEMS = {
    'aoi_boundary.gdb':                     'folder',  # Intermediate AOI GDB
    'one_status_common_datasets_aoi.gdb':   'folder',  # Common datasets GDB
    'one_status_tabs_1_and_2_datasets.gdb': 'folder',  # Tabs 1 & 2 datasets GDB
    'auto_status.log':                      'file',    # Per-run AST log file
    'input_list.json':                      'file',    # Per-run query manifest
}


def delete_item(item_path, item_type, logger=None):
    """
    Delete a single file or folder.
    
    Args:
        item_path: Full path to the item to delete
        item_type: Either 'file' or 'folder'
        logger: Optional logger instance
        
    Returns:
        True if deleted successfully, False otherwise
    """
    try:
        if not os.path.exists(item_path):
            return False
            
        if item_type == 'folder':
            shutil.rmtree(item_path)
            msg = f"Deleted folder: {item_path}"
        else:  # file
            os.remove(item_path)
            msg = f"Deleted file: {item_path}"
            
        if logger:
            logger.info(msg)
        else:
            print(msg)
        return True
        
    except Exception as e:
        error_msg = f"Error deleting {item_path}: {str(e)}"
        if logger:
            logger.error(error_msg)
        else:
            print(error_msg)
        return False


def delete_transitory_data_from_folder(folder_path, logger=None):
    """
    Delete transitory data from a single folder.
    
    Args:
        folder_path: Path to the folder to clean
        logger: Optional logger instance
        
    Returns:
        Dictionary with deletion statistics
    """
    stats = {
        'deleted': [],
        'not_found': [],
        'errors': []
    }
    
    if not os.path.exists(folder_path):
        msg = f"Folder does not exist: {folder_path}"
        if logger:
            logger.warning(msg)
        else:
            print(f"WARNING: {msg}")
        return stats
    
    msg = f"Processing folder: {folder_path}"
    if logger:
        logger.info(msg)
    else:
        print(msg)
    
    # Try to delete each transitory item
    for item_name, item_type in TRANSITORY_ITEMS.items():
        item_path = os.path.join(folder_path, item_name)
        
        if not os.path.exists(item_path):
            stats['not_found'].append(item_name)
            continue
        
        if delete_item(item_path, item_type, logger):
            stats['deleted'].append(item_name)
        else:
            stats['errors'].append(item_name)
    
    return stats


def delete_transitory_data_from_output_folder(output_root_folder, logger=None, recursive=True):
    """
    Delete transitory data from all subfolders in the output folder.
    
    Args:
        output_root_folder: Root output folder containing job output folders
        logger: Optional logger instance
        recursive: If True, search all subdirectories. If False, only process direct subfolders.
        
    Returns:
        Dictionary with overall statistics
    """
    overall_stats = {
        'folders_processed': 0,
        'total_deleted': 0,
        'total_not_found': 0,
        'total_errors': 0,
        'folder_details': {}
    }
    
    if not os.path.exists(output_root_folder):
        msg = f"Output root folder does not exist: {output_root_folder}"
        if logger:
            logger.error(msg)
        else:
            print(f"ERROR: {msg}")
        return overall_stats
    
    msg = f"Starting cleanup of output folder: {output_root_folder}"
    if logger:
        logger.info(msg)
    else:
        print(msg)
        print("=" * 80)
    
    # Iterate through folders
    if recursive:
        # Walk through all subdirectories
        for root, dirs, files in os.walk(output_root_folder):
            # Check if any transitory items exist in this folder
            has_transitory = any(
                item_name in dirs or item_name in files 
                for item_name in TRANSITORY_ITEMS.keys()
            )
            
            if has_transitory:
                stats = delete_transitory_data_from_folder(root, logger)
                overall_stats['folders_processed'] += 1
                overall_stats['total_deleted'] += len(stats['deleted'])
                overall_stats['total_not_found'] += len(stats['not_found'])
                overall_stats['total_errors'] += len(stats['errors'])
                overall_stats['folder_details'][root] = stats
    else:
        # Only process direct subfolders
        for item in os.listdir(output_root_folder):
            item_path = os.path.join(output_root_folder, item)
            if os.path.isdir(item_path):
                stats = delete_transitory_data_from_folder(item_path, logger)
                overall_stats['folders_processed'] += 1
                overall_stats['total_deleted'] += len(stats['deleted'])
                overall_stats['total_not_found'] += len(stats['not_found'])
                overall_stats['total_errors'] += len(stats['errors'])
                overall_stats['folder_details'][item_path] = stats
    
    # Print summary
    summary_msg = f"""
{'=' * 80}
Cleanup Summary:
  Folders processed: {overall_stats['folders_processed']}
  Total items deleted: {overall_stats['total_deleted']}
  Total items not found: {overall_stats['total_not_found']}
  Total errors: {overall_stats['total_errors']}
{'=' * 80}
"""
    if logger:
        logger.info(summary_msg)
    else:
        print(summary_msg)
    
    return overall_stats


def main():
    """
    Main function for standalone execution.
    """
    import argparse
    
    # Set up argument parser
    parser = argparse.ArgumentParser(
        description='Delete transitory data from AST output folders',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Transitory items that will be deleted:
  - aoi_boundary.gdb
  - one_status_common_datasets_aoi.gdb
  - one_status_tabs_1_and_2_datasets.gdb
  - auto_status.log
  - input_list.json

Examples:
  # Delete from default folder (searches all subfolders recursively)
  python delete_transitory_data.py
  
  # Delete from a specific folder (searches all subfolders recursively)
  python delete_transitory_data.py "C:\\output"
        """
    )
    
    parser.add_argument(
        'folder',
        nargs='?',
        default=DEFAULT_OUTPUT_FOLDER,
        help=f'Path to the output folder to clean (default: {DEFAULT_OUTPUT_FOLDER})'
    )
    
    parser.add_argument(
        '--single',
        action='store_true',
        help='Treat the folder as a single job folder (not a root output folder)'
    )
    
    parser.add_argument(
        '--log-file',
        help='Path to log file (optional)'
    )
    
    args = parser.parse_args()
    
    # Set up logging
    logger = None
    if args.log_file:
        logging.basicConfig(
            filename=args.log_file,
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s'
        )
        logger = logging.getLogger(__name__)
        logger.info("Starting delete_transitory_data.py")
    
    # Run the cleanup
    if args.single:
        # Process single folder
        stats = delete_transitory_data_from_folder(args.folder, logger)
        print(f"\nDeleted {len(stats['deleted'])} items")
        print(f"Not found: {len(stats['not_found'])} items")
        print(f"Errors: {len(stats['errors'])} items")
    else:
        # Process output root folder (always recursive)
        overall_stats = delete_transitory_data_from_output_folder(
            args.folder, 
            logger, 
            recursive=True
        )
    
    if logger:
        logger.info("Completed delete_transitory_data.py")
    
    print("\nCleanup complete!")


if __name__ == '__main__':
    main()
